---
name: Continuous integration
on: push
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2.0.2
      - name: Run the test suite
        run: PYTHONPATH=src pytest
