# See: https://github.com/github/super-linter
---
name: Linter
on:
  push:
    branches: [master]
    paths:
      - '**.md'
      - '**.py'
      - '**.yaml'
      - '**.yml'
  pull_request:
    branches: [master]
    paths:
      - '**.md'
      - '**.py'
      - '**.yaml'
      - '**.yml'
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2.0.2
      - name: Lint Markdown and YAML files
        uses: docker://github/super-linter:v3.3.0
        env:
          VALIDATE_MD: true
          VALIDATE_YAML: true
      - name: Lint Python source code
        uses: py-actions/flake8@v1
